name: terraform-platform

on:
  push:
    branches: [ "**" ]
    paths:
      - "infra/terraform/platform/**"
      - ".github/workflows/terraform-platform.yml"

permissions:
  id-token: write
  contents: read

jobs:
  tf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/557849827561/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "tf-admin@atlas-data-platform.iam.gserviceaccount.com"

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: infra/terraform/platform
        run: terraform init -backend-config=envs/dev/backend.hcl

      - name: Terraform plan
        working-directory: infra/terraform/platform
        run: terraform plan -var-file=envs/dev/terraform.tfvars

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra/terraform/platform
        run: terraform apply -auto-approve -var-file=envs/dev/terraform.tfvars
